[api]
host = "gitlab.com"
#token = "XXXXXXXXXXXXXXX"

[[projects]]
id = 13083
note = "https://gitlab.com/gitlab-org/gitlab-ce/tags"
remindingDay = 14

[[projects]]
id = 278964
note = "https://gitlab.com/gitlab-org/gitlab-ee/tags"
remindingDay = 7

[slack]
webhook = "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXX"
mention = "!here"
